"""update_language column to str

Revision ID: 10878499830f
Revises: 82df7c651068
Create Date: 2025-11-22 13:55:27.951285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '10878499830f'
down_revision: Union[str, Sequence[str], None] = '82df7c651068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'language',
               existing_type=mysql.ENUM('ENGLISH', 'HINDI', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'CHINESE', 'ARABIC'),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'language',
               existing_type=sa.String(length=5),
               type_=mysql.ENUM('ENGLISH', 'HINDI', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'CHINESE', 'ARABIC'),
               existing_nullable=False)
    # ### end Alembic commands ###
