"""feat: Restrict Agent language support and set default to Hindi ('hi')

Revision ID: 8003d760bbfa
Revises: 53d10589dfca
Create Date: 2025-11-20 19:52:36.372839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8003d760bbfa'
down_revision: Union[str, Sequence[str], None] = '53d10589dfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'language',
               existing_type=mysql.ENUM('ENGLISH', 'HINDI', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'CHINESE', 'ARABIC'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'language',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('ENGLISH', 'HINDI', 'SPANISH', 'FRENCH', 'GERMAN', 'JAPANESE', 'CHINESE', 'ARABIC'),
               existing_nullable=False)
    # ### end Alembic commands ###
