"""fix created_at with new api in agent,knowledge_docuemnt, process & tenant model

Revision ID: 82df7c651068
Revises: 53d10589dfca
Create Date: 2025-11-21 13:23:09.084915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82df7c651068'
down_revision: Union[str, Sequence[str], None] = '53d10589dfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
