"""Add file_path & file_type column on KnowledgeDocumentModel

Revision ID: da6e3224aac8
Revises: c1d18321d9b6
Create Date: 2025-11-17 16:12:20.661679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6e3224aac8'
down_revision: Union[str, Sequence[str], None] = 'c1d18321d9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('knowledge_documents', sa.Column('file_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'file_type')
    op.drop_column('knowledge_documents', 'file_path')
    # ### end Alembic commands ###
